// Nombre de país (como lo entrega GDELT) → ISO 3166-1 alfa-2, para derivar la bandera.
export const COUNTRY_ISO: Record<string, string> = {
  "united states": "US",
  "united kingdom": "GB",
  canada: "CA",
  australia: "AU",
  india: "IN",
  spain: "ES",
  france: "FR",
  germany: "DE",
  italy: "IT",
  brazil: "BR",
  mexico: "MX",
  argentina: "AR",
  colombia: "CO",
  russia: "RU",
  china: "CN",
  japan: "JP",
  "south korea": "KR",
  nigeria: "NG",
  "south africa": "ZA",
  ireland: "IE",
  netherlands: "NL",
  pakistan: "PK",
  indonesia: "ID",
  philippines: "PH",
  turkey: "TR",
  egypt: "EG",
  israel: "IL",
  "saudi arabia": "SA",
  "united arab emirates": "AE",
  switzerland: "CH",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  poland: "PL",
  ukraine: "UA",
  greece: "GR",
  portugal: "PT",
  "new zealand": "NZ",
  malaysia: "MY",
  singapore: "SG",
  thailand: "TH",
  vietnam: "VN",
  kenya: "KE",
  ghana: "GH",
  chile: "CL",
  peru: "PE",
  ecuador: "EC",
  venezuela: "VE",
  bangladesh: "BD",
  "sri lanka": "LK",
  iran: "IR",
  iraq: "IQ",
  afghanistan: "AF",
  morocco: "MA",
  algeria: "DZ",
  tunisia: "TN",
  ethiopia: "ET",
  tanzania: "TZ",
  uganda: "UG",
  zimbabwe: "ZW",
  austria: "AT",
  belgium: "BE",
  "czech republic": "CZ",
  hungary: "HU",
  romania: "RO",
  bulgaria: "BG",
  croatia: "HR",
  serbia: "RS",
  slovakia: "SK",
  slovenia: "SI",
  lithuania: "LT",
  latvia: "LV",
  estonia: "EE",
  iceland: "IS",
  luxembourg: "LU",
  qatar: "QA",
  kuwait: "KW",
  bahrain: "BH",
  oman: "OM",
  jordan: "JO",
  lebanon: "LB",
  syria: "SY",
  yemen: "YE",
  cuba: "CU",
  "dominican republic": "DO",
  guatemala: "GT",
  honduras: "HN",
  "el salvador": "SV",
  nicaragua: "NI",
  "costa rica": "CR",
  panama: "PA",
  bolivia: "BO",
  paraguay: "PY",
  uruguay: "UY",
  taiwan: "TW",
  "hong kong": "HK",
  myanmar: "MM",
};
