export type CountryInfo = { flag: string; en: string; es: string };

export const COUNTRIES: Record<string, CountryInfo> = {
  AF: { flag: "🇦🇫", en: "Afghanistan", es: "Afganistán" },
  AL: { flag: "🇦🇱", en: "Albania", es: "Albania" },
  DZ: { flag: "🇩🇿", en: "Algeria", es: "Argelia" },
  AO: { flag: "🇦🇴", en: "Angola", es: "Angola" },
  AQ: { flag: "🇦🇶", en: "Antarctica", es: "Antártida" },
  AR: { flag: "🇦🇷", en: "Argentina", es: "Argentina" },
  AM: { flag: "🇦🇲", en: "Armenia", es: "Armenia" },
  AU: { flag: "🇦🇺", en: "Australia", es: "Australia" },
  AT: { flag: "🇦🇹", en: "Austria", es: "Austria" },
  AZ: { flag: "🇦🇿", en: "Azerbaijan", es: "Azerbaiyán" },
  BD: { flag: "🇧🇩", en: "Bangladesh", es: "Bangladés" },
  BY: { flag: "🇧🇾", en: "Belarus", es: "Bielorrusia" },
  BE: { flag: "🇧🇪", en: "Belgium", es: "Bélgica" },
  BZ: { flag: "🇧🇿", en: "Belize", es: "Belice" },
  BJ: { flag: "🇧🇯", en: "Benin", es: "Benín" },
  BM: { flag: "🇧🇲", en: "Bermuda", es: "Bermudas" },
  BT: { flag: "🇧🇹", en: "Bhutan", es: "Bután" },
  BO: { flag: "🇧🇴", en: "Bolivia", es: "Bolivia" },
  BA: { flag: "🇧🇦", en: "Bosnia and Herzegovina", es: "Bosnia y Herzegovina" },
  BW: { flag: "🇧🇼", en: "Botswana", es: "Botsuana" },
  BR: { flag: "🇧🇷", en: "Brazil", es: "Brasil" },
  BN: { flag: "🇧🇳", en: "Brunei", es: "Brunéi" },
  BG: { flag: "🇧🇬", en: "Bulgaria", es: "Bulgaria" },
  BF: { flag: "🇧🇫", en: "Burkina Faso", es: "Burkina Faso" },
  BI: { flag: "🇧🇮", en: "Burundi", es: "Burundi" },
  KH: { flag: "🇰🇭", en: "Cambodia", es: "Camboya" },
  CM: { flag: "🇨🇲", en: "Cameroon", es: "Camerún" },
  CA: { flag: "🇨🇦", en: "Canada", es: "Canadá" },
  CF: {
    flag: "🇨🇫",
    en: "Central African Republic",
    es: "República Centroafricana",
  },
  TD: { flag: "🇹🇩", en: "Chad", es: "Chad" },
  CL: { flag: "🇨🇱", en: "Chile", es: "Chile" },
  CN: { flag: "🇨🇳", en: "China", es: "China" },
  CO: { flag: "🇨🇴", en: "Colombia", es: "Colombia" },
  CR: { flag: "🇨🇷", en: "Costa Rica", es: "Costa Rica" },
  HR: { flag: "🇭🇷", en: "Croatia", es: "Croacia" },
  CU: { flag: "🇨🇺", en: "Cuba", es: "Cuba" },
  CY: { flag: "🇨🇾", en: "Cyprus", es: "Chipre" },
  CZ: { flag: "🇨🇿", en: "Czech Republic", es: "República Checa" },
  CD: {
    flag: "🇨🇩",
    en: "Democratic Republic of the Congo",
    es: "República Democrática del Congo",
  },
  DK: { flag: "🇩🇰", en: "Denmark", es: "Dinamarca" },
  DJ: { flag: "🇩🇯", en: "Djibouti", es: "Yibuti" },
  DO: { flag: "🇩🇴", en: "Dominican Republic", es: "República Dominicana" },
  TL: { flag: "🇹🇱", en: "East Timor", es: "Timor Oriental" },
  EC: { flag: "🇪🇨", en: "Ecuador", es: "Ecuador" },
  EG: { flag: "🇪🇬", en: "Egypt", es: "Egipto" },
  SV: { flag: "🇸🇻", en: "El Salvador", es: "El Salvador" },
  GQ: { flag: "🇬🇶", en: "Equatorial Guinea", es: "Guinea Ecuatorial" },
  ER: { flag: "🇪🇷", en: "Eritrea", es: "Eritrea" },
  EE: { flag: "🇪🇪", en: "Estonia", es: "Estonia" },
  ET: { flag: "🇪🇹", en: "Ethiopia", es: "Etiopía" },
  FK: { flag: "🇫🇰", en: "Falkland Islands", es: "Islas Malvinas" },
  FJ: { flag: "🇫🇯", en: "Fiji", es: "Fiyi" },
  FI: { flag: "🇫🇮", en: "Finland", es: "Finlandia" },
  FR: { flag: "🇫🇷", en: "France", es: "Francia" },
  GF: { flag: "🇬🇫", en: "French Guiana", es: "Guayana Francesa" },
  TF: {
    flag: "🇹🇫",
    en: "French Southern and Antarctic Lands",
    es: "Territorios Australes Franceses",
  },
  GA: { flag: "🇬🇦", en: "Gabon", es: "Gabón" },
  GM: { flag: "🇬🇲", en: "Gambia", es: "Gambia" },
  GE: { flag: "🇬🇪", en: "Georgia", es: "Georgia" },
  DE: { flag: "🇩🇪", en: "Germany", es: "Alemania" },
  GH: { flag: "🇬🇭", en: "Ghana", es: "Ghana" },
  GR: { flag: "🇬🇷", en: "Greece", es: "Grecia" },
  GL: { flag: "🇬🇱", en: "Greenland", es: "Groenlandia" },
  GT: { flag: "🇬🇹", en: "Guatemala", es: "Guatemala" },
  GN: { flag: "🇬🇳", en: "Guinea", es: "Guinea" },
  GW: { flag: "🇬🇼", en: "Guinea Bissau", es: "Guinea-Bisáu" },
  GY: { flag: "🇬🇾", en: "Guyana", es: "Guyana" },
  HT: { flag: "🇭🇹", en: "Haiti", es: "Haití" },
  HN: { flag: "🇭🇳", en: "Honduras", es: "Honduras" },
  HU: { flag: "🇭🇺", en: "Hungary", es: "Hungría" },
  IS: { flag: "🇮🇸", en: "Iceland", es: "Islandia" },
  IN: { flag: "🇮🇳", en: "India", es: "India" },
  ID: { flag: "🇮🇩", en: "Indonesia", es: "Indonesia" },
  IR: { flag: "🇮🇷", en: "Iran", es: "Irán" },
  IQ: { flag: "🇮🇶", en: "Iraq", es: "Irak" },
  IE: { flag: "🇮🇪", en: "Ireland", es: "Irlanda" },
  IL: { flag: "🇮🇱", en: "Israel", es: "Israel" },
  IT: { flag: "🇮🇹", en: "Italy", es: "Italia" },
  CI: { flag: "🇨🇮", en: "Ivory Coast", es: "Costa de Marfil" },
  JM: { flag: "🇯🇲", en: "Jamaica", es: "Jamaica" },
  JP: { flag: "🇯🇵", en: "Japan", es: "Japón" },
  JO: { flag: "🇯🇴", en: "Jordan", es: "Jordania" },
  KZ: { flag: "🇰🇿", en: "Kazakhstan", es: "Kazajistán" },
  KE: { flag: "🇰🇪", en: "Kenya", es: "Kenia" },
  KW: { flag: "🇰🇼", en: "Kuwait", es: "Kuwait" },
  KG: { flag: "🇰🇬", en: "Kyrgyzstan", es: "Kirguistán" },
  LA: { flag: "🇱🇦", en: "Laos", es: "Laos" },
  LV: { flag: "🇱🇻", en: "Latvia", es: "Letonia" },
  LB: { flag: "🇱🇧", en: "Lebanon", es: "Líbano" },
  LS: { flag: "🇱🇸", en: "Lesotho", es: "Lesoto" },
  LR: { flag: "🇱🇷", en: "Liberia", es: "Liberia" },
  LY: { flag: "🇱🇾", en: "Libya", es: "Libia" },
  LT: { flag: "🇱🇹", en: "Lithuania", es: "Lituania" },
  LU: { flag: "🇱🇺", en: "Luxembourg", es: "Luxemburgo" },
  MK: { flag: "🇲🇰", en: "Macedonia", es: "Macedonia del Norte" },
  MG: { flag: "🇲🇬", en: "Madagascar", es: "Madagascar" },
  MW: { flag: "🇲🇼", en: "Malawi", es: "Malaui" },
  MY: { flag: "🇲🇾", en: "Malaysia", es: "Malasia" },
  ML: { flag: "🇲🇱", en: "Mali", es: "Malí" },
  MT: { flag: "🇲🇹", en: "Malta", es: "Malta" },
  MR: { flag: "🇲🇷", en: "Mauritania", es: "Mauritania" },
  MX: { flag: "🇲🇽", en: "Mexico", es: "México" },
  MD: { flag: "🇲🇩", en: "Moldova", es: "Moldavia" },
  MN: { flag: "🇲🇳", en: "Mongolia", es: "Mongolia" },
  ME: { flag: "🇲🇪", en: "Montenegro", es: "Montenegro" },
  MA: { flag: "🇲🇦", en: "Morocco", es: "Marruecos" },
  MZ: { flag: "🇲🇿", en: "Mozambique", es: "Mozambique" },
  MM: { flag: "🇲🇲", en: "Myanmar", es: "Birmania" },
  NA: { flag: "🇳🇦", en: "Namibia", es: "Namibia" },
  NP: { flag: "🇳🇵", en: "Nepal", es: "Nepal" },
  NL: { flag: "🇳🇱", en: "Netherlands", es: "Países Bajos" },
  NC: { flag: "🇳🇨", en: "New Caledonia", es: "Nueva Caledonia" },
  NZ: { flag: "🇳🇿", en: "New Zealand", es: "Nueva Zelanda" },
  NI: { flag: "🇳🇮", en: "Nicaragua", es: "Nicaragua" },
  NE: { flag: "🇳🇪", en: "Niger", es: "Níger" },
  NG: { flag: "🇳🇬", en: "Nigeria", es: "Nigeria" },
  KP: { flag: "🇰🇵", en: "North Korea", es: "Corea del Norte" },
  NO: { flag: "🇳🇴", en: "Norway", es: "Noruega" },
  OM: { flag: "🇴🇲", en: "Oman", es: "Omán" },
  PK: { flag: "🇵🇰", en: "Pakistan", es: "Pakistán" },
  PA: { flag: "🇵🇦", en: "Panama", es: "Panamá" },
  PG: { flag: "🇵🇬", en: "Papua New Guinea", es: "Papúa Nueva Guinea" },
  PY: { flag: "🇵🇾", en: "Paraguay", es: "Paraguay" },
  PE: { flag: "🇵🇪", en: "Peru", es: "Perú" },
  PH: { flag: "🇵🇭", en: "Philippines", es: "Filipinas" },
  PL: { flag: "🇵🇱", en: "Poland", es: "Polonia" },
  PT: { flag: "🇵🇹", en: "Portugal", es: "Portugal" },
  PR: { flag: "🇵🇷", en: "Puerto Rico", es: "Puerto Rico" },
  QA: { flag: "🇶🇦", en: "Qatar", es: "Catar" },
  RS: { flag: "🇷🇸", en: "Republic of Serbia", es: "Serbia" },
  CG: { flag: "🇨🇬", en: "Republic of the Congo", es: "Congo" },
  RO: { flag: "🇷🇴", en: "Romania", es: "Rumanía" },
  RU: { flag: "🇷🇺", en: "Russia", es: "Rusia" },
  RW: { flag: "🇷🇼", en: "Rwanda", es: "Ruanda" },
  SA: { flag: "🇸🇦", en: "Saudi Arabia", es: "Arabia Saudita" },
  SN: { flag: "🇸🇳", en: "Senegal", es: "Senegal" },
  SL: { flag: "🇸🇱", en: "Sierra Leone", es: "Sierra Leona" },
  SK: { flag: "🇸🇰", en: "Slovakia", es: "Eslovaquia" },
  SI: { flag: "🇸🇮", en: "Slovenia", es: "Eslovenia" },
  SB: { flag: "🇸🇧", en: "Solomon Islands", es: "Islas Salomón" },
  SO: { flag: "🇸🇴", en: "Somalia", es: "Somalia" },
  ZA: { flag: "🇿🇦", en: "South Africa", es: "Sudáfrica" },
  KR: { flag: "🇰🇷", en: "South Korea", es: "Corea del Sur" },
  SS: { flag: "🇸🇸", en: "South Sudan", es: "Sudán del Sur" },
  ES: { flag: "🇪🇸", en: "Spain", es: "España" },
  LK: { flag: "🇱🇰", en: "Sri Lanka", es: "Sri Lanka" },
  SD: { flag: "🇸🇩", en: "Sudan", es: "Sudán" },
  SR: { flag: "🇸🇷", en: "Suriname", es: "Surinam" },
  SZ: { flag: "🇸🇿", en: "Swaziland", es: "Suazilandia" },
  SE: { flag: "🇸🇪", en: "Sweden", es: "Suecia" },
  CH: { flag: "🇨🇭", en: "Switzerland", es: "Suiza" },
  SY: { flag: "🇸🇾", en: "Syria", es: "Siria" },
  TW: { flag: "🇹🇼", en: "Taiwan", es: "Taiwán" },
  TJ: { flag: "🇹🇯", en: "Tajikistan", es: "Tayikistán" },
  TH: { flag: "🇹🇭", en: "Thailand", es: "Tailandia" },
  BS: { flag: "🇧🇸", en: "The Bahamas", es: "Bahamas" },
  TG: { flag: "🇹🇬", en: "Togo", es: "Togo" },
  TT: { flag: "🇹🇹", en: "Trinidad and Tobago", es: "Trinidad y Tobago" },
  TN: { flag: "🇹🇳", en: "Tunisia", es: "Túnez" },
  TR: { flag: "🇹🇷", en: "Turkey", es: "Turquía" },
  TM: { flag: "🇹🇲", en: "Turkmenistan", es: "Turkmenistán" },
  UG: { flag: "🇺🇬", en: "Uganda", es: "Uganda" },
  UA: { flag: "🇺🇦", en: "Ukraine", es: "Ucrania" },
  AE: { flag: "🇦🇪", en: "United Arab Emirates", es: "Emiratos Árabes Unidos" },
  GB: { flag: "🇬🇧", en: "United Kingdom", es: "Reino Unido" },
  TZ: { flag: "🇹🇿", en: "United Republic of Tanzania", es: "Tanzania" },
  US: { flag: "🇺🇸", en: "United States of America", es: "Estados Unidos" },
  UY: { flag: "🇺🇾", en: "Uruguay", es: "Uruguay" },
  UZ: { flag: "🇺🇿", en: "Uzbekistan", es: "Uzbekistán" },
  VU: { flag: "🇻🇺", en: "Vanuatu", es: "Vanuatu" },
  VE: { flag: "🇻🇪", en: "Venezuela", es: "Venezuela" },
  VN: { flag: "🇻🇳", en: "Vietnam", es: "Vietnam" },
  PS: { flag: "🇵🇸", en: "West Bank", es: "Palestina" },
  EH: { flag: "", en: "Western Sahara", es: "Western Sahara" },
  YE: { flag: "🇾🇪", en: "Yemen", es: "Yemen" },
  ZM: { flag: "🇿🇲", en: "Zambia", es: "Zambia" },
  ZW: { flag: "🇿🇼", en: "Zimbabwe", es: "Zimbabue" },
};

export const COUNTRY_BY_NAME: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRIES).map(([code, info]) => [info.en, code]),
);
