// Palabras vacías ES/EN: ruido que dominaría el ranking de tendencias.
export const STOPWORDS = [
  "para", "por", "con", "sin", "sobre", "entre", "desde", "hasta", "como",
  "pero", "porque", "cuando", "donde", "quien", "cual", "este", "esta",
  "estos", "estas", "ese", "esa", "esos", "esas", "aquel", "todo", "toda",
  "todos", "todas", "otro", "otra", "otros", "otras", "mismo", "misma",
  "muy", "mas", "más", "menos", "tambien", "también", "solo", "sólo",
  "ya", "aun", "aún", "aunque", "sera", "será", "son", "fue", "fueron",
  "han", "hay", "haber", "tiene", "tienen", "hace", "hacer", "puede",
  "pueden", "debe", "deben", "dijo", "dice", "según", "segun", "tras",
  "ante", "bajo", "cada", "una", "unos", "unas", "del", "las", "los",
  "que", "the", "and", "for", "with", "from", "this", "that", "these",
  "those", "have", "has", "had", "will", "would", "could", "should",
  "been", "being", "was", "were", "are", "its", "his", "her", "their",
  "they", "them", "there", "here", "what", "when", "where", "which",
  "who", "whom", "how", "why", "after", "before", "over", "under",
  "into", "about", "against", "between", "during", "than", "then",
  "more", "most", "some", "such", "only", "also", "just", "new",
  "says", "said", "say", "get", "got", "make", "made", "one", "two",
  "not", "but", "all", "can", "may", "out", "off", "now", "day",
  "days", "year", "years", "week", "time", "news", "video", "live",
];
